### ISSUE TITLE
Some questions about source code.

### ISSUE THREAD

**Issue by VQHieu1012** [aliwister/wildgraph#1]
In your paper, you proposed using a Variational Autoencoder (VAE), but in the source code, you only implemented a Sequential layer for the encoder-decoder and did not include Positional Encoding. I have trained the model, but the results are significantly different from what you reported in the paper. different from your result in the paper. Did I miss something?

**Comment by aliwister** [comment]
Which file are you looking at? Our method is implemented in wildgraph.py:

This is where the PE is encoded.
`                if (self.hparams.pe == 1):
                    x_encoded = torch.concat([z.squeeze(), x.squeeze(), pos], dim=0)`

**Comment by VQHieu1012** [comment]
Thanks for pointing me out. However, I want to know more about Variational Recurrent Network (VRN). But I haven't found the code snipped to implement this. The only code snipped I found is encoder - decoder in _create_model() function in wildgraph.py using linear layers. I am not too familiar with torch. Sorry for the inconvenience. Can you help me about this. Thank you.

**Comment by VQHieu1012** [comment]
Thanks for the paper.
